name: visionary
description: A comprehensive Flutter eye health application with AI-powered features

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: "^1.0.8"
  provider: "^6.1.5+1"
  shared_preferences: "^2.5.3"
  http: ^1.1.0
  camera: ^0.10.5+9
  image_picker: ^1.0.4
  permission_handler: ^11.1.0
  flutter_animate: ^4.2.0+1
  google_fonts: ^6.1.0
  flutter_staggered_animations: ^1.1.1
  lottie: ^2.7.0
  connectivity_plus: "^5.0.2"
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  flutter_local_notifications: ^16.3.0
  # AI dependencies (replace with your actual AI package)
  google_generative_ai: ^0.3.2
  firebase_core: ^2.25.2
  firebase_app_check: ^0.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
  
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
