// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeFnHekGWHN-9WO4XtoA6t_l1a8EPO0LU',
    appId: '1:862371581041:web:baa34e54eedd9a32dc5fd0',
    messagingSenderId: '862371581041',
    projectId: 'eyeconnect-65sog',
    authDomain: 'eyeconnect-65sog.firebaseapp.com',
    storageBucket: 'eyeconnect-65sog.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUyEiLX7u1B2B-biAx51lBJNnQDFXvhKw',
    appId: '1:862371581041:android:0b25ab82ebf95676dc5fd0',
    messagingSenderId: '862371581041',
    projectId: 'eyeconnect-65sog',
    storageBucket: 'eyeconnect-65sog.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_0EWhFuRm3VFsj_g1VM72zY4NkpMikNU',
    appId: '1:862371581041:ios:77ee3a55a88f273cdc5fd0',
    messagingSenderId: '862371581041',
    projectId: 'eyeconnect-65sog',
    storageBucket: 'eyeconnect-65sog.firebasestorage.app',
    iosClientId: '862371581041-4p5g1cpel1t3e95mdl9ncjn9qegraa7o.apps.googleusercontent.com',
    iosBundleId: 'com.jmr.visionary.visionary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_0EWhFuRm3VFsj_g1VM72zY4NkpMikNU',
    appId: '1:862371581041:ios:77ee3a55a88f273cdc5fd0',
    messagingSenderId: '862371581041',
    projectId: 'eyeconnect-65sog',
    storageBucket: 'eyeconnect-65sog.firebasestorage.app',
    iosClientId: '862371581041-4p5g1cpel1t3e95mdl9ncjn9qegraa7o.apps.googleusercontent.com',
    iosBundleId: 'com.jmr.visionary.visionary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeFnHekGWHN-9WO4XtoA6t_l1a8EPO0LU',
    appId: '1:862371581041:web:f87fb83a8361d110dc5fd0',
    messagingSenderId: '862371581041',
    projectId: 'eyeconnect-65sog',
    authDomain: 'eyeconnect-65sog.firebaseapp.com',
    storageBucket: 'eyeconnect-65sog.firebasestorage.app',
  );

}